import { useState } from "react";
import { Link } from "react-router-dom";
import {
  Check,
  ArrowRight,
  Phone,
  Mail,
  MapPin,
  Shield,
  Zap,
  Sun,
  Home,
  Building2,
  BatteryCharging,
  Wrench,
  ChevronDown,
  Star,
  Cpu,
} from "lucide-react";
import { FadeIn } from "../components/ui/FadeIn";
import { Button } from "../components/ui/Button";
import { PartnersMarquee } from "../components/PartnersMarquee";
import { SEO } from "../components/SEO";
import { QuoteForm } from "../components/QuoteForm";
import { LocationMapCard, OFFICE_LOCATIONS } from "../components/LocationMap";
import { PRIMARY_PHONE, PRIMARY_PHONE_RAW } from "../lib/constants";

const trustChips = [
  "CEC Accredited Installer",
  "Solar & Battery Solutions",
  "Grid Connection Support",
  "Battery Storage",
];

const systemTypes = [
  {
    title: "Residential Solar",
    href: "/solar-systems/residential-solar-system",
    icon: Home,
    text: "Fannie Bay homes vary widely in age and layout, from heritage-era houses to newer townhouses and apartments, so we design each solar system around your household's real energy use rather than a standard package. Every install includes cyclone rated mounting, built to hold firm through wet season weather.",
  },
  {
    title: "Commercial Solar",
    href: "/solar-systems/commercial-solar-system",
    icon: Building2,
    text: "Fannie Bay businesses can benefit from a solar system designed around their operating hours, electricity use and available roof space. We provide tailored commercial solar solutions to help businesses generate their own power and reduce reliance on grid electricity.",
  },
  {
    title: "Battery Backup Solar",
    href: "/solar-systems/off-grid-solar-system",
    icon: BatteryCharging,
    text: "Fannie Bay properties looking for greater energy independence can benefit from a solar system paired with battery storage. We design battery-backed solutions that store excess solar energy for later use, helping you make more of your own electricity when your panels aren't generating.",
  },
];

const relatedServices = [
  {
    title: "Solar Inverter Installation",
    href: "/services/solar-inverters/installation",
    icon: Cpu,
    text: "The inverter is at the heart of your solar power system, converting the electricity generated by your panels into usable power for your property. We install appropriately sized, high-quality inverters designed for local conditions and matched to your energy requirements, rooftop solar system and future needs.",
  },
  {
    title: "Solar Inverter Repair",
    href: "/services/solar-inverters/repair",
    icon: Wrench,
    text: "If your Fannie Bay solar system is producing less power than expected, frequent inverter faults or system shutdowns could be the cause. Our team can inspect the system, identify the fault and carry out the required inverter repairs across major brands and models, helping restore reliable solar performance.",
  },
  {
    title: "Solar Battery Installation",
    href: "/services/solar-battery-installation",
    icon: BatteryCharging,
    text: "Battery systems with MPPT technology can efficiently track available solar power and direct excess energy into storage. We install appropriately sized battery solutions for Fannie Bay homes and businesses, helping you make greater use of your solar energy and reduce reliance on grid electricity.",
  },
  {
    title: "EV Charger Installation",
    href: "/services/ev-chargers/installation",
    icon: Zap,
    text: "Pair your EV charger with solar power and use more of the electricity your system generates. We install EV charging solutions for Fannie Bay homes and businesses, with the charger configured to suit your existing solar system and electrical capacity.",
  },
  {
    title: "EV Charger Repair",
    href: "/services/ev-chargers/repair",
    icon: Wrench,
    text: "An EV charger that stops working can disrupt your daily routine. Our team can inspect charging equipment, identify electrical or connection faults and provide professional repair services where required. We help Fannie Bay property owners keep their EV charging setup safe and dependable.",
  },
];

const whyPoints = [
  "Local solar service for homes and businesses throughout Fannie Bay",
  "Fast response for new solar installations, system faults and repairs",
  "Professional solar system inspections for older or underperforming systems",
  "Solar maintenance and support to help keep your system performing efficiently",
  "SAA Accredited Installers using approved and certified solar equipment",
  "Solar solutions selected for Darwin's heat, humidity and demanding local conditions",
  "Federal STC Solar PV Grant accounted for in your solar quote from the beginning",
  "Cheaper Home Batteries Program discount available on eligible battery installations",
  "Assistance with Power and Water/Jacana Energy grid connection requirements",
  "Complete solar solutions including panels, inverters, batteries and EV chargers",
  "Local support from a Darwin-based solar team familiar with Fannie Bay and surrounding suburbs",
  "Backed by genuine local customer reviews and professional solar service",
];

const faqs = [
  {
    q: "What is the best solar installation and repair service in Fannie Bay NT?",
    a: "The right solar installer should offer professional system design, quality solar equipment, reliable installation and ongoing repair support. OneRoof Solar provides solar installation, inverter, battery and repair services for homes and businesses in Fannie Bay.",
  },
  {
    q: "How much does solar installation and repair cost in Fannie Bay NT?",
    a: "The cost depends on your property, system size, roof space, electricity usage, equipment and whether you need a new installation, repair or upgrade. OneRoof Solar can assess your requirements and provide a tailored quote for your Fannie Bay property.",
  },
  {
    q: "What solar services are available in Fannie Bay NT?",
    a: "OneRoof Solar provides solar panel installation, solar system repairs, inverter solutions, battery storage, EV charger installation and system upgrades for residential and commercial properties across Fannie Bay.",
  },
  {
    q: "Can I get my existing solar system repaired in Fannie Bay?",
    a: "Yes. If your solar system has reduced output, inverter faults or other performance issues, a professional inspection can identify the underlying problem. OneRoof Solar provides solar diagnostics, repairs and replacement solutions for existing systems in Fannie Bay.",
  },
  {
    q: "How do I choose a solar installer in Fannie Bay?",
    a: "Look for an installer that can assess your energy usage and property, recommend a suitable solar system, handle professional installation and provide support after installation. OneRoof Solar offers tailored solar solutions for Fannie Bay homes and businesses.",
  },
];

export function FannieBayPage() {
  const [openFaqIndex, setOpenFaqIndex] = useState<number | null>(0);
  const darwinOffice = OFFICE_LOCATIONS[0];

  const seoData = {
    title: "Solar Panels & Installers in Fannie Bay NT | OneRoof Solar",
    metaDescription:
      "Looking for solar in Fannie Bay? OneRoof Solar provides solar panel installation, inverter, battery and EV charger solutions for homes and businesses. Get a free quote.",
    canonicalUrl: "https://oneroofsolar.com.au/locations/fannie-bay/",
    robots: "index, follow",
    openGraphTitle: "Solar Panels & Installers in Fannie Bay NT | OneRoof Solar",
    openGraphDescription:
      "Looking for solar in Fannie Bay? OneRoof Solar provides solar panel installation, inverter, battery and EV charger solutions for homes and businesses. Get a free quote.",
    twitterTitle: "Solar Panels & Installers in Fannie Bay NT | OneRoof Solar",
    twitterDescription:
      "Looking for solar in Fannie Bay? OneRoof Solar provides solar panel installation, inverter, battery and EV charger solutions for homes and businesses. Get a free quote.",
  };

  const schemas = [
    {
      "@context": "https://schema.org",
      "@type": "Service",
      name: "Solar Installation and Repair Fannie Bay",
      provider: {
        "@type": "LocalBusiness",
        name: "Oneroof Solar",
        image: "/assets/images/home/logo-oneroof.png",
        telephone: PRIMARY_PHONE,
        email: "info@oneroofsolar.com.au",
        address: {
          "@type": "PostalAddress",
          streetAddress: "3/97 Pruen Rd",
          addressLocality: "Berrimah",
          addressRegion: "NT",
          postalCode: "0828",
          addressCountry: "AU",
        },
      },
      areaServed: [
        { "@type": "AdministrativeArea", name: "Fannie Bay" },
        { "@type": "AdministrativeArea", name: "Darwin" },
      ],
      description:
        "Solar panel installation, battery storage, inverter solutions and solar repairs for residential and commercial properties across Fannie Bay.",
    },
    {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      mainEntity: faqs.map((faq) => ({
        "@type": "Question",
        name: faq.q,
        acceptedAnswer: {
          "@type": "Answer",
          text: faq.a,
        },
      })),
    },
    {
      "@context": "https://schema.org",
      "@type": "BreadcrumbList",
      itemListElement: [
        {
          "@type": "ListItem",
          position: 1,
          name: "Home",
          item: "https://oneroofsolar.com.au/",
        },
        {
          "@type": "ListItem",
          position: 2,
          name: "Locations",
          item: "https://oneroofsolar.com.au/contact/",
        },
        {
          "@type": "ListItem",
          position: 3,
          name: "Fannie Bay",
          item: "https://oneroofsolar.com.au/locations/fannie-bay/",
        },
      ],
    },
    {
      "@context": "https://schema.org",
      "@type": "LocalBusiness",
      name: "Oneroof Solar Fannie Bay",
      image: "/assets/images/home/logo-oneroof.png",
      telephone: PRIMARY_PHONE,
      email: "info@oneroofsolar.com.au",
      address: {
        "@type": "PostalAddress",
        streetAddress: "3/97 Pruen Rd",
        addressLocality: "Berrimah",
        addressRegion: "NT",
        postalCode: "0828",
        addressCountry: "AU",
      },
      geo: {
        "@type": "GeoCoordinates",
        latitude: -12.4328,
        longitude: 130.8415,
      },
      url: "https://oneroofsolar.com.au/locations/fannie-bay/",
      aggregateRating: {
        "@type": "AggregateRating",
        ratingValue: "4.9",
        reviewCount: "128",
      },
      serviceArea: [
        { "@type": "Place", name: "Fannie Bay" },
        { "@type": "Place", name: "Parap" },
        { "@type": "Place", name: "Larrakeyah" },
        { "@type": "Place", name: "Darwin" },
      ],
    },
  ];

  return (
    <div className="bg-white text-slate-900 font-sans min-h-screen">
      <SEO seo={seoData} />

      {schemas.map((schema, index) => (
        <script
          key={index}
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
        />
      ))}

      {/* Hero */}
      <section className="relative pt-14 pb-20 lg:pt-20 lg:pb-32 overflow-hidden bg-[#0A1118]">
        <div className="absolute inset-0">
          <div className="absolute inset-0 bg-[#121814]/40 mix-blend-multiply" />
          <div className="absolute inset-0 bg-gradient-to-t from-[#121814] via-transparent to-[#0A1118]/30" />
        </div>

        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <FadeIn isHero>
              <nav
                aria-label="Breadcrumb"
                className="flex items-center gap-2 text-slate-400 text-xs font-semibold uppercase tracking-wider mb-6"
              >
                <a
                  href="https://oneroofsolar.com.au/"
                  className="hover:text-[#8cc63f] transition-colors"
                >
                  Home
                </a>
                <span className="text-slate-500" aria-hidden="true">
                  &gt;
                </span>
                <span className="text-slate-400">Locations</span>
                <span className="text-slate-500" aria-hidden="true">
                  &gt;
                </span>
                <span className="text-[#8cc63f]" aria-current="page">
                  Fannie Bay
                </span>
              </nav>

              <h1 className="hero-heading text-white mb-6 break-words normal-case">
                Solar Installation and Repair in{" "}
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-brand-500 to-brand-300">
                  Fannie Bay NT
                </span>
              </h1>

              <p className="text-base sm:text-lg text-slate-300 leading-relaxed mb-8 font-medium border-l-2 border-[#8cc63f] pl-6">
                Power your Fannie Bay property with a solar system designed around your actual energy
                needs. OneRoof Solar provides solar panel installation, battery storage, inverter
                solutions and solar repairs for residential and commercial properties across Fannie
                Bay. Whether you are upgrading an existing system or looking to generate more of your
                own electricity, our Darwin-based team can take care of the system design,
                installation and grid connection process.
              </p>

              <div className="flex flex-wrap gap-4">
                <Button
                  size="lg"
                  className="rounded-xl px-8 bg-[#8cc63f] text-[#19281D] border-none font-bold hover:bg-brand-400 transition-all h-14 hover:-translate-y-1 shadow-[0_4px_20px_rgba(91,201,77,0.3)] uppercase tracking-wider text-xs"
                  asChild
                >
                  <a href="#quote-form">Get a Free Fannie Bay Solar Quote</a>
                </Button>
                <Button
                  size="lg"
                  variant="outline"
                  className="rounded-xl px-8 text-white border-white/20 bg-white/5 font-bold hover:bg-white/10 hover:text-white hover:border-white/30 transition-all h-14 hover:-translate-y-1 uppercase tracking-wider text-xs"
                  asChild
                >
                  <a href={`tel:${PRIMARY_PHONE_RAW}`}>Call {PRIMARY_PHONE}</a>
                </Button>
              </div>

              <div className="flex flex-wrap gap-x-6 gap-y-2 mt-8">
                {trustChips.map((chip) => (
                  <div
                    key={chip}
                    className="flex items-center gap-2 text-slate-300 text-xs sm:text-sm font-semibold"
                  >
                    <Check className="w-4 h-4 text-[#8cc63f] shrink-0" />
                    {chip}
                  </div>
                ))}
              </div>
            </FadeIn>

            <FadeIn isHero delay={0.2} className="relative">
              <div className="relative group rounded-[2.5rem] overflow-hidden border border-white/10 shadow-2xl bg-slate-900/40 aspect-[4/3] flex items-center justify-center">
                <img
                  fetchPriority="high"
                  src="/assets/images/hosted/bayview-0820.webp"
                  alt="Solar installation serving Fannie Bay homes and businesses near Darwin"
                  className="w-full h-full object-cover relative z-10 transition-transform duration-700 group-hover:scale-[1.02]"
                />
                <div className="absolute top-6 right-6 bg-[#0A1118]/95 backdrop-blur-md border border-[#8cc63f]/30 px-5 py-3 rounded-2xl z-20 shadow-lg text-center">
                  <div className="flex items-center justify-center gap-1 text-2xl font-black text-[#8cc63f] leading-none">
                    4.9 <Star className="w-4 h-4 fill-[#8cc63f]" />
                  </div>
                  <div className="text-[9px] text-slate-300 uppercase tracking-widest font-bold mt-1">
                    128 Reviews
                  </div>
                </div>
              </div>
            </FadeIn>
          </div>
        </div>
      </section>

      <PartnersMarquee />

      {/* Intro */}
      <section className="py-20 bg-white relative border-b border-slate-200">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
          <FadeIn>
            <h2 className="text-[2rem] font-bold leading-[1.25] tracking-tight text-center text-slate-900 mb-8 normal-case">
              Solar Panel Installation and Repair in Fannie Bay
            </h2>
            <div className="text-slate-600 text-base sm:text-lg leading-relaxed font-medium space-y-6">
              <p>
                Fannie Bay is an established Darwin suburb with a mix of houses, townhouses and
                apartments. OneRoof Solar designs solar systems around your property&apos;s roof
                space, electricity use and energy needs, whether you&apos;re near the Fannie Bay
                Foreshore, East Point Road or the local shopping area.
              </p>
              <p>
                We also repair existing solar systems, including inverter faults and reduced solar
                output. Our team diagnoses the underlying issue before recommending the right repair,
                replacement or upgrade for your system.
              </p>
            </div>
          </FadeIn>
        </div>
      </section>

      {/* Residential / Commercial / Battery */}
      <section className="py-24 bg-slate-50 relative border-b border-slate-200">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-3xl mx-auto mb-16">
            <FadeIn>
              <h2 className="text-[2rem] font-bold leading-[1.25] tracking-tight text-slate-900 mb-4 normal-case">
                Solar Options for Fannie Bay Homes and Businesses
              </h2>
            </FadeIn>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {systemTypes.map((item, i) => {
              const Icon = item.icon;
              return (
                <FadeIn
                  key={item.title}
                  delay={0.1 * (i + 1)}
                  className="bg-white rounded-[2rem] p-8 border border-slate-200 hover:border-[#8cc63f]/40 transition-all duration-300 hover:-translate-y-1 flex flex-col h-full shadow-sm"
                >
                  <div className="w-12 h-12 rounded-xl bg-[#8cc63f]/10 flex items-center justify-center text-[#8cc63f] border border-[#8cc63f]/20 mb-6 shadow-inner">
                    <Icon className="w-6 h-6" />
                  </div>
                  <h3 className="text-xl font-black text-slate-900 mb-4 tracking-tight normal-case">
                    {item.title}
                  </h3>
                  <p className="text-slate-600 text-sm sm:text-base font-medium leading-relaxed flex-1 mb-6">
                    {item.text}
                  </p>
                  <Link
                    to={item.href}
                    className="inline-flex items-center gap-2 text-[#8cc63f] font-bold text-sm hover:gap-3 transition-all"
                  >
                    Read More <ArrowRight className="w-4 h-4" />
                  </Link>
                </FadeIn>
              );
            })}
          </div>
        </div>
      </section>

      {/* Mid CTA 1 */}
      <section className="py-12 lg:py-16 bg-white border-b border-slate-200 relative">
        <div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">
          <FadeIn>
            <div className="bg-[#0A1118] border border-brand-500/30 p-8 sm:p-12 rounded-2xl sm:rounded-3xl text-center shadow-xl">
              <h3 className="text-2xl sm:text-3xl font-black text-white mb-3 tracking-tight normal-case">
                Solar Designed for Fannie Bay&apos;s Character Homes
              </h3>
              <p className="text-slate-300 text-sm sm:text-base mb-8 max-w-2xl mx-auto">
                Quality solar systems with STC incentives included in your quote.
              </p>
              <a
                href="#quote-form"
                className="inline-block bg-[#8cc63f] text-[#19281D] px-8 py-4 rounded-xl font-bold transition-all hover:bg-brand-400 hover:-translate-y-0.5 uppercase tracking-wider text-xs"
              >
                Get Your Fannie Bay Quote &rarr;
              </a>
            </div>
          </FadeIn>
        </div>
      </section>

      {/* Related services */}
      <section className="py-24 bg-slate-50 relative border-b border-slate-200">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-3xl mx-auto mb-16">
            <FadeIn>
              <h2 className="text-[2rem] font-bold leading-[1.25] tracking-tight text-slate-900 mb-4 normal-case">
                Inverters, Batteries, and EV Chargers for Fannie Bay
              </h2>
              <p className="text-slate-600 text-sm sm:text-base leading-relaxed">
                A reliable solar system depends on more than quality panels. Your inverter needs to
                handle Darwin&apos;s heat and humidity, while battery storage and EV charging can help
                you get more value from the energy your system produces. OneRoof Solar provides
                complete solar solutions for homes and businesses throughout Fannie Bay, from
                installation and system upgrades to repairs and ongoing support.
              </p>
            </FadeIn>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {relatedServices.map((item, i) => {
              const Icon = item.icon;
              return (
                <FadeIn
                  key={item.title}
                  delay={Math.min(0.05 * i, 0.25)}
                  className={`bg-white rounded-[2rem] p-8 border border-slate-200 hover:border-[#8cc63f]/40 transition-all duration-300 hover:-translate-y-1 flex flex-col h-full shadow-sm ${
                    i === relatedServices.length - 1 && relatedServices.length % 3 === 2
                      ? "md:col-span-2 lg:col-span-1"
                      : ""
                  }`}
                >
                  <div className="w-12 h-12 rounded-xl bg-[#8cc63f]/10 flex items-center justify-center text-[#8cc63f] border border-[#8cc63f]/20 mb-6">
                    <Icon className="w-6 h-6" />
                  </div>
                  <h3 className="text-xl font-black text-slate-900 mb-4 tracking-tight normal-case">
                    {item.title}
                  </h3>
                  <p className="text-slate-600 text-sm leading-relaxed flex-1 mb-6">{item.text}</p>
                  <Link
                    to={item.href}
                    className="inline-flex items-center gap-2 text-[#8cc63f] font-bold text-sm hover:gap-3 transition-all"
                  >
                    Read More <ArrowRight className="w-4 h-4" />
                  </Link>
                </FadeIn>
              );
            })}
          </div>
        </div>
      </section>

      {/* Why choose */}
      <section className="py-24 bg-white relative border-b border-slate-200">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-16 items-start">
            <FadeIn>
              <h2 className="text-[2rem] font-bold leading-[1.25] tracking-tight text-slate-900 mb-8 normal-case">
                Why Fannie Bay Chooses OneRoof Solar
              </h2>
              <ul className="space-y-5">
                {whyPoints.map((point) => (
                  <li key={point} className="flex items-start gap-4">
                    <div className="w-8 h-8 rounded-full bg-[#8cc63f]/10 flex items-center justify-center text-[#8cc63f] border border-[#8cc63f]/20 shrink-0 mt-0.5">
                      <Check className="w-4 h-4" />
                    </div>
                    <span className="text-slate-600 text-base sm:text-lg font-medium leading-relaxed">
                      {point}
                    </span>
                  </li>
                ))}
              </ul>
            </FadeIn>

            <FadeIn delay={0.15}>
              <div className="bg-slate-50 rounded-[2rem] p-8 border border-slate-200 shadow-sm sticky top-28">
                <div className="w-12 h-12 rounded-xl bg-[#8cc63f]/10 flex items-center justify-center text-[#8cc63f] border border-[#8cc63f]/20 mb-6">
                  <Shield className="w-6 h-6" />
                </div>
                <h3 className="text-xl font-black text-slate-900 tracking-tight mb-3 normal-case">
                  Built for Territory Conditions
                </h3>
                <p className="text-slate-600 text-sm leading-relaxed mb-6">
                  From cyclone-rated mounting to quality inverters and upfront STC incentives,
                  every Fannie Bay system is designed around Darwin&apos;s heat, humidity and wet
                  season.
                </p>
                <div className="flex items-center gap-3 text-slate-900 font-bold">
                  <Sun className="w-5 h-5 text-[#8cc63f]" />
                  Local Berrimah-based team
                </div>
              </div>
            </FadeIn>
          </div>
        </div>
      </section>

      {/* Repair CTA */}
      <section className="py-12 lg:py-16 bg-slate-50 border-b border-slate-200 relative">
        <div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">
          <FadeIn>
            <div className="bg-[#0A1118] border border-brand-500/30 p-8 sm:p-12 rounded-2xl sm:rounded-3xl text-center shadow-xl">
              <h3 className="text-2xl sm:text-3xl font-black text-white mb-3 tracking-tight normal-case">
                Solar System Not Working Properly in Fannie Bay?
              </h3>
              <p className="text-slate-300 text-sm sm:text-base mb-8 max-w-2xl mx-auto">
                Get expert diagnostics and reliable repairs for your solar system.
              </p>
              <div className="flex flex-wrap justify-center gap-4">
                <a
                  href="#quote-form"
                  className="inline-block bg-[#8cc63f] text-[#19281D] px-8 py-4 rounded-xl font-bold transition-all hover:bg-brand-400 hover:-translate-y-0.5 uppercase tracking-wider text-xs"
                >
                  Book Your Fannie Bay Solar Service
                </a>
                <a
                  href={`tel:${PRIMARY_PHONE_RAW}`}
                  className="inline-block bg-white/5 text-white border border-white/20 px-8 py-4 rounded-xl font-bold transition-all hover:bg-white/10 hover:-translate-y-0.5 uppercase tracking-wider text-xs"
                >
                  Call {PRIMARY_PHONE}
                </a>
              </div>
            </div>
          </FadeIn>
        </div>
      </section>

      {/* Map */}
      <section className="py-24 bg-white relative border-b border-slate-200">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <FadeIn>
              <h2 className="text-[2rem] font-bold leading-[1.25] tracking-tight text-slate-900 mb-6 normal-case">
                Servicing Fannie Bay
              </h2>
              <p className="text-slate-600 text-base sm:text-lg leading-relaxed font-medium mb-6">
                OneRoof Solar provides solar installation, repairs and energy solutions across Fannie
                Bay and surrounding Darwin suburbs. From homes near the Fannie Bay Foreshore and East
                Point Road to properties close to the local shops, our Darwin-based team can provide
                on-site solar services when you need them. We also service nearby areas including
                Parap, Larrakeyah and the Darwin CBD, making it easy to arrange professional solar
                support close to home.
              </p>
              <div className="flex items-start gap-3 text-slate-700 font-medium">
                <MapPin className="w-5 h-5 text-[#8cc63f] shrink-0 mt-0.5" />
                <span>{darwinOffice.address}</span>
              </div>
            </FadeIn>
            <FadeIn delay={0.15}>
              <LocationMapCard location={darwinOffice} />
            </FadeIn>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-24 bg-slate-50 relative border-b border-slate-200">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-8 items-start">
            <div className="lg:col-span-5 lg:sticky-below-header">
              <FadeIn>
                <h2 className="text-[2rem] font-bold leading-[1.25] tracking-tight text-slate-900 mb-6 normal-case">
                  Frequently Asked Questions
                </h2>
                <p className="text-base sm:text-lg text-slate-600 leading-relaxed font-medium mb-8 max-w-md">
                  Common questions about solar installation and repair for Fannie Bay properties.
                </p>
                <a href="#quote-form">
                  <Button className="rounded-xl shadow-lg hover:-translate-y-1 transition-all h-14 px-8 font-bold bg-[#8cc63f] text-[#19281D] hover:bg-brand-400 border-none uppercase tracking-wider text-xs">
                    Get a Free Quote
                  </Button>
                </a>
              </FadeIn>
            </div>

            <div className="lg:col-span-7 space-y-4">
              {faqs.map((faq, i) => {
                const isOpen = openFaqIndex === i;
                return (
                  <FadeIn key={faq.q} delay={i * 0.05}>
                    <div
                      className={`border rounded-2xl overflow-hidden transition-all duration-300 ${
                        isOpen
                          ? "bg-white shadow-md border-brand-500/50"
                          : "bg-white border-slate-200 hover:border-brand-500/30 shadow-sm"
                      }`}
                    >
                      <button
                        onClick={() => setOpenFaqIndex(isOpen ? null : i)}
                        aria-expanded={isOpen}
                        aria-controls={`fannie-bay-faq-panel-${i}`}
                        id={`fannie-bay-faq-button-${i}`}
                        className="w-full text-left px-6 py-5 sm:p-6 flex items-start sm:items-center justify-between focus:outline-none gap-4"
                      >
                        <div className="flex items-start sm:items-center gap-4">
                          <div
                            className={`shrink-0 w-8 h-8 sm:w-10 sm:h-10 rounded-full flex items-center justify-center font-bold text-xs sm:text-sm transition-colors ${
                              isOpen
                                ? "bg-[#8cc63f] text-[#19281D] shadow-md shadow-[#8cc63f]/20"
                                : "bg-slate-50 text-slate-500 border border-slate-200"
                            }`}
                          >
                            0{i + 1}
                          </div>
                          <h3
                            className={`text-sm sm:text-base font-bold leading-tight transition-colors ${
                              isOpen ? "text-[#8cc63f]" : "text-slate-900"
                            }`}
                          >
                            {faq.q}
                          </h3>
                        </div>
                        <div
                          className={`shrink-0 w-8 h-8 rounded-full flex items-center justify-center border transition-all duration-300 ${
                            isOpen
                              ? "border-[#8cc63f] bg-[#8cc63f]/10 text-[#8cc63f] rotate-180"
                              : "border-slate-200 text-slate-500 bg-slate-50"
                          }`}
                        >
                          <ChevronDown className="w-4 h-4" />
                        </div>
                      </button>
                      <div
                        id={`fannie-bay-faq-panel-${i}`}
                        aria-labelledby={`fannie-bay-faq-button-${i}`}
                        role="region"
                        className={`overflow-hidden transition-all duration-500 px-6 ${
                          isOpen ? "max-h-96 pb-6 opacity-100" : "max-h-0 opacity-0"
                        }`}
                      >
                        <div className="text-slate-600 leading-relaxed font-medium pl-12 sm:pl-14 text-xs sm:text-sm">
                          {faq.a}
                        </div>
                      </div>
                    </div>
                  </FadeIn>
                );
              })}
            </div>
          </div>
        </div>
      </section>

      {/* Quote form */}
      <section id="quote-form" className="py-24 bg-[#0A1118] relative">
        <div className="absolute inset-0 overflow-hidden pointer-events-none" aria-hidden="true">
          <div className="absolute bottom-0 left-0 w-[500px] h-[500px] bg-[#8cc63f]/5 rounded-full blur-[120px] translate-y-1/3 -translate-x-1/3" />
        </div>

        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-start">
            <div className="lg:sticky-below-header">
              <FadeIn>
                <h2 className="text-[2rem] font-bold leading-[1.25] tracking-tight text-white mb-6 normal-case">
                  Ready to Cut Your Fannie Bay Energy Costs?
                </h2>
                <p className="text-slate-300 text-base sm:text-lg leading-relaxed font-medium mb-8">
                  Get a tailored solar solution with STC incentives included in your quote and
                  support with your Power and Water grid connection requirements. OneRoof Solar makes
                  switching to solar simple from system design through installation.
                </p>

                <div className="space-y-6">
                  <a
                    href={`tel:${PRIMARY_PHONE_RAW}`}
                    className="flex items-center gap-4 text-white hover:text-[#8cc63f] transition-colors group"
                  >
                    <div className="w-12 h-12 rounded-full bg-white/5 flex items-center justify-center text-[#8cc63f] border border-white/10 group-hover:bg-[#8cc63f] group-hover:text-[#19281D] transition-all">
                      <Phone className="w-5 h-5" />
                    </div>
                    <div>
                      <div className="text-xs text-slate-400 font-bold uppercase tracking-wider">
                        Call Our Team
                      </div>
                      <div className="text-base sm:text-lg font-black">{PRIMARY_PHONE}</div>
                    </div>
                  </a>

                  <a
                    href="mailto:info@oneroofsolar.com.au"
                    className="flex items-center gap-4 text-white hover:text-[#8cc63f] transition-colors group"
                  >
                    <div className="w-12 h-12 rounded-full bg-white/5 flex items-center justify-center text-[#8cc63f] border border-white/10 group-hover:bg-[#8cc63f] group-hover:text-[#19281D] transition-all">
                      <Mail className="w-5 h-5" />
                    </div>
                    <div>
                      <div className="text-xs text-slate-400 font-bold uppercase tracking-wider">
                        Email Inquiry
                      </div>
                      <div className="text-base sm:text-lg font-black">info@oneroofsolar.com.au</div>
                    </div>
                  </a>
                </div>
              </FadeIn>
            </div>

            <FadeIn delay={0.2}>
              <QuoteForm
                title="Book Your Free Fannie Bay Consultation"
                defaultInterest="Residential Solar Panels"
                source="location_fannie_bay"
              />
            </FadeIn>
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-24 bg-[#0A1118] text-center relative border-t border-white/5">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
          <FadeIn>
            <h3 className="text-3xl sm:text-4xl font-black text-white mb-4 tracking-tight normal-case">
              Ready to Cut Your Fannie Bay Energy Costs?
            </h3>
            <p className="text-slate-300 text-base sm:text-lg mb-8 max-w-2xl mx-auto">
              Get a tailored solar solution with STC incentives included in your quote and support
              with your Power and Water grid connection requirements.
            </p>
            <a
              href="#quote-form"
              className="inline-block bg-[#8cc63f] text-[#19281D] px-10 py-5 rounded-xl font-bold transition-all hover:bg-brand-400 hover:-translate-y-1 shadow-[0_4px_20px_rgba(91,201,77,0.3)] uppercase tracking-wider text-xs"
            >
              Book Your Fannie Bay Solar Consultation &rarr;
            </a>
          </FadeIn>
        </div>
      </section>
    </div>
  );
}

export default FannieBayPage;
